spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.107.24.31:3306/blog?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: fzshuai
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

logging:
  level:
    root: warn
    com.fzshuai: info
  file:
    name: log/blog-pro.log

server:
  port: 8089
  ssl:
    key-store: classpath:www.fzshuai.top.jks
    key-store-password: 353v8cj82l
    key-store-type: JKS