version: '3'

services:
  mysql:
    image: mysql:8.0.36
    container_name: mysql
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      # root 密码
      MYSQL_ROOT_PASSWORD: 123456
      # 初始化数据库(后续的初始化sql会在这个库执行)
      MYSQL_DATABASE: fzshuai_blog
    ports:
      - "3306:3306"
    volumes:
      # 数据挂载
      - /docker/mysql/data/:/var/lib/mysql/
      # 配置挂载
      - /docker/mysql/conf/:/etc/mysql/conf.d/
      # 让容器的时钟与宿主机时钟同步，避免时区的问题，ro是read only的意思，就是只读
      - /etc/localtime:/etc/localtime:ro
    command:
      # 将mysql8.0默认密码策略 修改为 原先 策略 (mysql8.0对其默认策略做了更改 会导致密码无法匹配)
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 512M
    privileged: true
    network_mode: "host"

  nginx-web:
    image: nginx:1.25.4
    container_name: nginx-web
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # 证书映射
      - /docker/nginx/cert:/etc/nginx/cert
      # 配置文件映射
      - /docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      # 页面目录
      - /docker/nginx/html:/usr/share/nginx/html
      # 日志目录
      - /docker/nginx/log:/var/log/nginx
      # 让容器的时钟与宿主机时钟同步
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    network_mode: "host"

  redis:
    image: redis:7.2.4
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    volumes:
      # 配置文件
      - /docker/redis/conf:/redis/config:rw
      # 数据文件
      - /docker/redis/data/:/redis/data/:rw
      # 让容器的时钟与宿主机时钟同步
      - /etc/localtime:/etc/localtime:ro
    command: "redis-server /redis/config/redis.conf"
    privileged: true
    network_mode: "host"

  minio:
    image: minio/minio:RELEASE.2023-03-24T21-41-23Z
    container_name: minio
    ports:
      # api 端口
      - "9000:9000"
      # 控制台端口
      - "9001:9001"
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      # 管理后台用户名
      MINIO_ROOT_USER: adminminio
      # 管理后台密码，最小8个字符
      MINIO_ROOT_PASSWORD: adminminio
      # 开启压缩 on 开启 off 关闭
      MINIO_COMPRESS: "off"
      # 扩展名 .pdf,.doc 为空 所有类型均压缩
      MINIO_COMPRESS_EXTENSIONS: ""
      # mime 类型 application/pdf 为空 所有类型均压缩
      MINIO_COMPRESS_MIME_TYPES: ""
    volumes:
      # 映射当前目录下的data目录至容器内/data目录
      - /docker/minio/data:/data
      # 映射配置目录
      - /docker/minio/config:/root/.minio/
      # 让容器的时钟与宿主机时钟同步
      - /etc/localtime:/etc/localtime:ro
    command: server --address ':9000' --console-address ':9001' /data  # 指定容器中的目录 /data
    privileged: true
    network_mode: "host"

  rabbitmq:
    image: rabbitmq:3.12.13-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      # 控制台账号密码
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      # 数据文件
      - /docker/rabbitmq/data:/var/lib/rabbitmq
      # 挂载日志
      - /docker/rabbitmq/log:/var/log/rabbitmq
      # 让容器的时钟与宿主机时钟同步
      - /etc/localtime:/etc/localtime:ro
    command: rabbitmq-server
    privileged: true
    network_mode: "host"


  fzshuai-server1:
    image: fzshuai/fzshuai-server:2.1.0
    container_name: fzshuai-server1
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      SERVER_PORT: 8080
    volumes:
      # 配置文件
      - /docker/server1/logs/:/fzshuai/server/logs/
      # 让容器的时钟与宿主机时钟同步
      - /etc/localtime:/etc/localtime:ro
      # skywalking 探针
#      - /docker/skywalking/agent/:/fzshuai/skywalking/agent
    privileged: true
    network_mode: "host"

  fzshuai-server2:
    image: fzshuai/fzshuai-server:2.1.0
    container_name: fzshuai-server2
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      SERVER_PORT: 8081
    volumes:
      # 配置文件
      - /docker/server2/logs/:/fzshuai/server/logs/
      # 让容器的时钟与宿主机时钟同步
      - /etc/localtime:/etc/localtime:ro
      # skywalking 探针
#      - /docker/skywalking/agent/:/fzshuai/skywalking/agent
    privileged: true
    network_mode: "host"

  fzshuai-monitor-admin:
    image: fzshuai/fzshuai-monitor-admin:2.1.0
    container_name: fzshuai-monitor-admin
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    volumes:
      # 配置文件
      - /docker/monitor/logs/:/fzshuai/monitor/logs
      # 让容器的时钟与宿主机时钟同步
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    network_mode: "host"

  fzshuai-xxl-job-admin:
    image: fzshuai/fzshuai-xxl-job-admin:2.1.0
    container_name: fzshuai-xxl-job-admin
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    volumes:
      # 配置文件
      - /docker/xxljob/logs/:/fzshuai/xxljob/logs
      # 让容器的时钟与宿主机时钟同步
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    network_mode: "host"
